export const CREATE_SONG = "CREATE_SONG";
export const RETRIEVE_SONGS = "RETRIEVE_SONGS";
export const RETRIEVE_SONG = "RETRIEVE_SONG";
export const UPDATE_SONG = "UPDATE_SONG";
export const DELETE_SONG = "DELETE_SONG";